name: Build robot code
on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    container: wpilib/systemcore-cross-ubuntu:2025-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: photonlib-offline
          run-id: 16460285110
          repository: photonvision/photonvision
          github-token: ${{ secrets.ARTIFACT_DOWNLOADER }}
          artifact-ids: 3879505423

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build
