name: Build robot code
on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    container: wpilib/systemcore-cross-ubuntu:2025-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Look at file structure
        run: ls -ltr -a
#      - name: Download PhotonVision
#        run: curl -L https://api.github.com/repos/PhotonVision/photonvision/actions/artifacts/3601960507/zip | tar -zx -C ~/wpilib/2027_alpha1/

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build --stacktrace --info
